module.exports = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  MISSING_AUTHORIZATION_HEADER: 'MISSING_AUTHORIZATION_HEADER',
  MISSING_AUTHORIZATION_HEADER_VALUE: 'MISSING_AUTHORIZATION_HEADER_VALUE',
  INVALID_AUTHORIZATION_PREFIX: 'INVALID_AUTHORIZATION_PREFIX',
  USER_CREATION_FAILURE: 'USER_CREATION_FAILURE',
  USER_RETRIEVAL_FAILURE: 'USER_RETRIEVAL_FAILURE',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE'
};
